const MAIN_ROUTE = '/';
const LOGIN_ROUTE = '/login';
const REGISTER_ROUTE = '/register';
const TODO_CREATE_ROUTE = '/todo-input';

const ROUTES = [MAIN_ROUTE, LOGIN_ROUTE, REGISTER_ROUTE, TODO_CREATE_ROUTE];

export { MAIN_ROUTE, LOGIN_ROUTE, REGISTER_ROUTE, TODO_CREATE_ROUTE, ROUTES };
